<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use Illuminate\Support\Facades\DB;
use App\Models\Division;
use App\Models\District;
use App\Models\Upazila;

class UpazilaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $upazilasData = [
            ['upazila' => 'Amtali', 'district' => 'Barguna', 'division' => 'Barisal'],
            ['upazila' => 'Bamna', 'district' => 'Barguna', 'division' => 'Barisal'],
            ['upazila' => 'Barguna-S', 'district' => 'Barguna', 'division' => 'Barisal'],
            ['upazila' => 'Betagi', 'district' => 'Barguna', 'division' => 'Barisal'],
            ['upazila' => 'Patharghata', 'district' => 'Barguna', 'division' => 'Barisal'],
            ['upazila' => 'Taltali', 'district' => 'Barguna', 'division' => 'Barisal'],
            ['upazila' => 'Agailjhara', 'district' => 'Barisal', 'division' => 'Barisal'],
            ['upazila' => 'Babuganj', 'district' => 'Barisal', 'division' => 'Barisal'],
            ['upazila' => 'Bakerganj', 'district' => 'Barisal', 'division' => 'Barisal'],
            ['upazila' => 'Banaripara', 'district' => 'Barisal', 'division' => 'Barisal'],
            ['upazila' => 'Barishal-S', 'district' => 'Barisal', 'division' => 'Barisal'],
            ['upazila' => 'Gouranadi', 'district' => 'Barisal', 'division' => 'Barisal'],
            ['upazila' => 'Hizla', 'district' => 'Barisal', 'division' => 'Barisal'],
            ['upazila' => 'Mehendiganj', 'district' => 'Barisal', 'division' => 'Barisal'],
            ['upazila' => 'Muladi', 'district' => 'Barisal', 'division' => 'Barisal'],
            ['upazila' => 'Uzirpur', 'district' => 'Barisal', 'division' => 'Barisal'],
            ['upazila' => 'Bhola-S', 'district' => 'Bhola', 'division' => 'Barisal'],
            ['upazila' => 'Borhanuddin', 'district' => 'Bhola', 'division' => 'Barisal'],
            ['upazila' => 'Charfassion', 'district' => 'Bhola', 'division' => 'Barisal'],
            ['upazila' => 'Daulatkhan', 'district' => 'Bhola', 'division' => 'Barisal'],
            ['upazila' => 'Lalmohan', 'district' => 'Bhola', 'division' => 'Barisal'],
            ['upazila' => 'Monpura', 'district' => 'Bhola', 'division' => 'Barisal'],
            ['upazila' => 'Tazumuddin', 'district' => 'Bhola', 'division' => 'Barisal'],
            ['upazila' => 'Jhalokathi-S', 'district' => 'Jhalokati', 'division' => 'Barisal'],
            ['upazila' => 'Kathalia', 'district' => 'Jhalokati', 'division' => 'Barisal'],
            ['upazila' => 'Nalchity', 'district' => 'Jhalokati', 'division' => 'Barisal'],
            ['upazila' => 'Rajapur', 'district' => 'Jhalokati', 'division' => 'Barisal'],
            ['upazila' => 'Bauphal', 'district' => 'Patuakhali', 'division' => 'Barisal'],
            ['upazila' => 'Dashmina', 'district' => 'Patuakhali', 'division' => 'Barisal'],
            ['upazila' => 'Dumki', 'district' => 'Patuakhali', 'division' => 'Barisal'],
            ['upazila' => 'Galachipa', 'district' => 'Patuakhali', 'division' => 'Barisal'],
            ['upazila' => 'Kalapara', 'district' => 'Patuakhali', 'division' => 'Barisal'],
            ['upazila' => 'Mirjaganj', 'district' => 'Patuakhali', 'division' => 'Barisal'],
            ['upazila' => 'Patuakhali-S', 'district' => 'Patuakhali', 'division' => 'Barisal'],
            ['upazila' => 'Rangabali', 'district' => 'Patuakhali', 'division' => 'Barisal'],
            ['upazila' => 'Bhandaria', 'district' => 'Pirojpur', 'division' => 'Barisal'],
            ['upazila' => 'Kawkhali', 'district' => 'Pirojpur', 'division' => 'Barisal'],
            ['upazila' => 'Mothbaria', 'district' => 'Pirojpur', 'division' => 'Barisal'],
            ['upazila' => 'Nazirpur', 'district' => 'Pirojpur', 'division' => 'Barisal'],
            ['upazila' => 'Nesarabad', 'district' => 'Pirojpur', 'division' => 'Barisal'],
            ['upazila' => 'Pirojpur-S', 'district' => 'Pirojpur', 'division' => 'Barisal'],
            ['upazila' => 'Zianagar', 'district' => 'Pirojpur', 'division' => 'Barisal'],
            ['upazila' => 'Akhaura', 'district' => 'Brahmanbaria', 'division' => 'Chattogram'],
            ['upazila' => 'Ashuganj', 'district' => 'Brahmanbaria', 'division' => 'Chattogram'],
            ['upazila' => 'B.Baria-S', 'district' => 'Brahmanbaria', 'division' => 'Chattogram'],
            ['upazila' => 'Bancharampur', 'district' => 'Brahmanbaria', 'division' => 'Chattogram'],
            ['upazila' => 'Bijoynagar', 'district' => 'Brahmanbaria', 'division' => 'Chattogram'],
            ['upazila' => 'Kasba', 'district' => 'Brahmanbaria', 'division' => 'Chattogram'],
            ['upazila' => 'Nabinagar', 'district' => 'Brahmanbaria', 'division' => 'Chattogram'],
            ['upazila' => 'Nasirnagar', 'district' => 'Brahmanbaria', 'division' => 'Chattogram'],
            ['upazila' => 'Sarail', 'district' => 'Brahmanbaria', 'division' => 'Chattogram'],
            ['upazila' => 'Alikadam', 'district' => 'Bandarban', 'division' => 'Chattogram'],
            ['upazila' => 'Bandarban-S', 'district' => 'Bandarban', 'division' => 'Chattogram'],
            ['upazila' => 'Lama', 'district' => 'Bandarban', 'division' => 'Chattogram'],
            ['upazila' => 'Naikhyongchari', 'district' => 'Bandarban', 'division' => 'Chattogram'],
            ['upazila' => 'Rowangchari', 'district' => 'Bandarban', 'division' => 'Chattogram'],
            ['upazila' => 'Ruma', 'district' => 'Bandarban', 'division' => 'Chattogram'],
            ['upazila' => 'Thanchi', 'district' => 'Bandarban', 'division' => 'Chattogram'],
            ['upazila' => 'Chandpur-S', 'district' => 'Chandpur', 'division' => 'Chattogram'],
            ['upazila' => 'Faridganj', 'district' => 'Chandpur', 'division' => 'Chattogram'],
            ['upazila' => 'Haimchar', 'district' => 'Chandpur', 'division' => 'Chattogram'],
            ['upazila' => 'Haziganj', 'district' => 'Chandpur', 'division' => 'Chattogram'],
            ['upazila' => 'Kachua', 'district' => 'Chandpur', 'division' => 'Chattogram'],
            ['upazila' => 'Matlab (Dakshin)', 'district' => 'Chandpur', 'division' => 'Chattogram'],
            ['upazila' => 'Matlab (Uttar)', 'district' => 'Chandpur', 'division' => 'Chattogram'],
            ['upazila' => 'Shahrasti', 'district' => 'Chandpur', 'division' => 'Chattogram'],
            ['upazila' => 'Anwara', 'district' => 'Chattogram', 'division' => 'Chattogram'],
            ['upazila' => 'Banskhali', 'district' => 'Chattogram', 'division' => 'Chattogram'],
            ['upazila' => 'Boalkhali', 'district' => 'Chattogram', 'division' => 'Chattogram'],
            ['upazila' => 'Chandanish', 'district' => 'Chattogram', 'division' => 'Chattogram'],
            ['upazila' => 'Fatikchari', 'district' => 'Chattogram', 'division' => 'Chattogram'],
            ['upazila' => 'Hathazari', 'district' => 'Chattogram', 'division' => 'Chattogram'],
            ['upazila' => 'Karnaphuli', 'district' => 'Chattogram', 'division' => 'Chattogram'],
            ['upazila' => 'Lohagara', 'district' => 'Chattogram', 'division' => 'Chattogram'],
            ['upazila' => 'Mirsharai', 'district' => 'Chattogram', 'division' => 'Chattogram'],
            ['upazila' => 'Patiya', 'district' => 'Chattogram', 'division' => 'Chattogram'],
            ['upazila' => 'Rangunia', 'district' => 'Chattogram', 'division' => 'Chattogram'],
            ['upazila' => 'Raojan', 'district' => 'Chattogram', 'division' => 'Chattogram'],
            ['upazila' => 'Sandwip', 'district' => 'Chattogram', 'division' => 'Chattogram'],
            ['upazila' => 'Satkania', 'district' => 'Chattogram', 'division' => 'Chattogram'],
            ['upazila' => 'Sitakunda', 'district' => 'Chattogram', 'division' => 'Chattogram'],
            ['upazila' => 'Chakoria', 'district' => 'Cox\'s Bazar', 'division' => 'Chattogram'],
            ['upazila' => 'Cox\'S Bazar-S', 'district' => 'Cox\'s Bazar', 'division' => 'Chattogram'],
            ['upazila' => 'Kutubdia', 'district' => 'Cox\'s Bazar', 'division' => 'Chattogram'],
            ['upazila' => 'Moheskhali', 'district' => 'Cox\'s Bazar', 'division' => 'Chattogram'],
            ['upazila' => 'Pekua', 'district' => 'Cox\'s Bazar', 'division' => 'Chattogram'],
            ['upazila' => 'Ramu', 'district' => 'Cox\'s Bazar', 'division' => 'Chattogram'],
            ['upazila' => 'Teknaf', 'district' => 'Cox\'s Bazar', 'division' => 'Chattogram'],
            ['upazila' => 'Ukhiya', 'district' => 'Cox\'s Bazar', 'division' => 'Chattogram'],
            ['upazila' => 'Barura', 'district' => 'Cumilla', 'division' => 'Chattogram'],
            ['upazila' => 'Brahmanpara', 'district' => 'Cumilla', 'division' => 'Chattogram'],
            ['upazila' => 'Burichong', 'district' => 'Cumilla', 'division' => 'Chattogram'],
            ['upazila' => 'Chandina', 'district' => 'Cumilla', 'division' => 'Chattogram'],
            ['upazila' => 'Chouddagram', 'district' => 'Cumilla', 'division' => 'Chattogram'],
            ['upazila' => 'Cumilla-S', 'district' => 'Cumilla', 'division' => 'Chattogram'],
            ['upazila' => 'Cumilla-S Daksin', 'district' => 'Cumilla', 'division' => 'Chattogram'],
            ['upazila' => 'Daudkandi', 'district' => 'Cumilla', 'division' => 'Chattogram'],
            ['upazila' => 'Debidwar', 'district' => 'Cumilla', 'division' => 'Chattogram'],
            ['upazila' => 'Homna', 'district' => 'Cumilla', 'division' => 'Chattogram'],
            ['upazila' => 'Laksham', 'district' => 'Cumilla', 'division' => 'Chattogram'],
            ['upazila' => 'Lalmai', 'district' => 'Cumilla', 'division' => 'Chattogram'],
            ['upazila' => 'Meghna', 'district' => 'Cumilla', 'division' => 'Chattogram'],
            ['upazila' => 'Monohorganj', 'district' => 'Cumilla', 'division' => 'Chattogram'],
            ['upazila' => 'Muradnagar', 'district' => 'Cumilla', 'division' => 'Chattogram'],
            ['upazila' => 'Nangalkot', 'district' => 'Cumilla', 'division' => 'Chattogram'],
            ['upazila' => 'Titas', 'district' => 'Cumilla', 'division' => 'Chattogram'],
            ['upazila' => 'Chhagalniya', 'district' => 'Feni', 'division' => 'Chattogram'],
            ['upazila' => 'Daganbhuiyan', 'district' => 'Feni', 'division' => 'Chattogram'],
            ['upazila' => 'Feni-S', 'district' => 'Feni', 'division' => 'Chattogram'],
            ['upazila' => 'Fulgazi', 'district' => 'Feni', 'division' => 'Chattogram'],
            ['upazila' => 'Porshuram', 'district' => 'Feni', 'division' => 'Chattogram'],
            ['upazila' => 'Sonagazi', 'district' => 'Feni', 'division' => 'Chattogram'],
            ['upazila' => 'Dighinala', 'district' => 'Khagrachari', 'division' => 'Chattogram'],
            ['upazila' => 'Guimara', 'district' => 'Khagrachari', 'division' => 'Chattogram'],
            ['upazila' => 'Khagrachari-S', 'district' => 'Khagrachari', 'division' => 'Chattogram'],
            ['upazila' => 'Laxmichari', 'district' => 'Khagrachari', 'division' => 'Chattogram'],
            ['upazila' => 'Mahalchari', 'district' => 'Khagrachari', 'division' => 'Chattogram'],
            ['upazila' => 'Manikchari', 'district' => 'Khagrachari', 'division' => 'Chattogram'],
            ['upazila' => 'Matiranga', 'district' => 'Khagrachari', 'division' => 'Chattogram'],
            ['upazila' => 'Panchari', 'district' => 'Khagrachari', 'division' => 'Chattogram'],
            ['upazila' => 'Ramgarh', 'district' => 'Khagrachari', 'division' => 'Chattogram'],
            ['upazila' => 'Komol Nagar', 'district' => 'Lakshmipur', 'division' => 'Chattogram'],
            ['upazila' => 'Lakshmipur-S', 'district' => 'Lakshmipur', 'division' => 'Chattogram'],
            ['upazila' => 'Raipur', 'district' => 'Lakshmipur', 'division' => 'Chattogram'],
            ['upazila' => 'Ramganj', 'district' => 'Lakshmipur', 'division' => 'Chattogram'],
            ['upazila' => 'Ramgati', 'district' => 'Lakshmipur', 'division' => 'Chattogram'],
            ['upazila' => 'Begumganj', 'district' => 'Noakhali', 'division' => 'Chattogram'],
            ['upazila' => 'Chatkhil', 'district' => 'Noakhali', 'division' => 'Chattogram'],
            ['upazila' => 'Companiganj', 'district' => 'Noakhali', 'division' => 'Chattogram'],
            ['upazila' => 'Hatiya', 'district' => 'Noakhali', 'division' => 'Chattogram'],
            ['upazila' => 'Kabir Hat', 'district' => 'Noakhali', 'division' => 'Chattogram'],
            ['upazila' => 'Noakhali-S', 'district' => 'Noakhali', 'division' => 'Chattogram'],
            ['upazila' => 'Senbag', 'district' => 'Noakhali', 'division' => 'Chattogram'],
            ['upazila' => 'Sonaimuri', 'district' => 'Noakhali', 'division' => 'Chattogram'],
            ['upazila' => 'Subarna Char', 'district' => 'Noakhali', 'division' => 'Chattogram'],
            ['upazila' => 'Baghaichari', 'district' => 'Rangamati', 'division' => 'Chattogram'],
            ['upazila' => 'Barkal', 'district' => 'Rangamati', 'division' => 'Chattogram'],
            ['upazila' => 'Belaichari', 'district' => 'Rangamati', 'division' => 'Chattogram'],
            ['upazila' => 'Juraichari', 'district' => 'Rangamati', 'division' => 'Chattogram'],
            ['upazila' => 'Kaptai', 'district' => 'Rangamati', 'division' => 'Chattogram'],
            ['upazila' => 'Kaukhali', 'district' => 'Rangamati', 'division' => 'Chattogram'],
            ['upazila' => 'Langadu', 'district' => 'Rangamati', 'division' => 'Chattogram'],
            ['upazila' => 'Nanniarchar', 'district' => 'Rangamati', 'division' => 'Chattogram'],
            ['upazila' => 'Rajosthali', 'district' => 'Rangamati', 'division' => 'Chattogram'],
            ['upazila' => 'Rangamati-S', 'district' => 'Rangamati', 'division' => 'Chattogram'],
            ['upazila' => 'Dhamrai', 'district' => 'Dhaka', 'division' => 'Dhaka'],
            ['upazila' => 'Dohar', 'district' => 'Dhaka', 'division' => 'Dhaka'],
            ['upazila' => 'Keraniganj', 'district' => 'Dhaka', 'division' => 'Dhaka'], 
            ['upazila' => 'Nawabganj', 'district' => 'Dhaka', 'division' => 'Dhaka'],
            ['upazila' => 'Savar', 'district' => 'Dhaka', 'division' => 'Dhaka'],
            ['upazila' => 'Alfadanga', 'district' => 'Faridpur', 'division' => 'Dhaka'],
            ['upazila' => 'Bhanga', 'district' => 'Faridpur', 'division' => 'Dhaka'],
            ['upazila' => 'Boalmari', 'district' => 'Faridpur', 'division' => 'Dhaka'],
            ['upazila' => 'Charbhadrasan', 'district' => 'Faridpur', 'division' => 'Dhaka'],
            ['upazila' => 'Faridpur-S', 'district' => 'Faridpur', 'division' => 'Dhaka'],
            ['upazila' => 'Madhukhali', 'district' => 'Faridpur', 'division' => 'Dhaka'],
            ['upazila' => 'Nagarkanda', 'district' => 'Faridpur', 'division' => 'Dhaka'],
            ['upazila' => 'Sadarpur', 'district' => 'Faridpur', 'division' => 'Dhaka'],
            ['upazila' => 'Saltha', 'district' => 'Faridpur', 'division' => 'Dhaka'],
            ['upazila' => 'Gazipur-S', 'district' => 'Gazipur', 'division' => 'Dhaka'],
            ['upazila' => 'Kaliakoir', 'district' => 'Gazipur', 'division' => 'Dhaka'],
            ['upazila' => 'Kaliganj', 'district' => 'Gazipur', 'division' => 'Dhaka'],
            ['upazila' => 'Kapasia', 'district' => 'Gazipur', 'division' => 'Dhaka'],
            ['upazila' => 'Sreepur', 'district' => 'Gazipur', 'division' => 'Dhaka'],
            ['upazila' => 'Gopalganj-S', 'district' => 'Gopalganj', 'division' => 'Dhaka'],
            ['upazila' => 'Kasiani', 'district' => 'Gopalganj', 'division' => 'Dhaka'],
            ['upazila' => 'Kotwalipara', 'district' => 'Gopalganj', 'division' => 'Dhaka'],
            ['upazila' => 'Muksudpur', 'district' => 'Gopalganj', 'division' => 'Dhaka'],
            ['upazila' => 'Tungipara', 'district' => 'Gopalganj', 'division' => 'Dhaka'],
            ['upazila' => 'Austagram', 'district' => 'Kishoreganj', 'division' => 'Dhaka'],
            ['upazila' => 'Bajitpur', 'district' => 'Kishoreganj', 'division' => 'Dhaka'],
            ['upazila' => 'Bhairab', 'district' => 'Kishoreganj', 'division' => 'Dhaka'],
            ['upazila' => 'Hossainpur', 'district' => 'Kishoreganj', 'division' => 'Dhaka'],
            ['upazila' => 'Itna', 'district' => 'Kishoreganj', 'division' => 'Dhaka'],
            ['upazila' => 'Karimganj', 'district' => 'Kishoreganj', 'division' => 'Dhaka'],
            ['upazila' => 'Kishoreganj-S', 'district' => 'Kishoreganj', 'division' => 'Dhaka'],
            ['upazila' => 'Kuliarchar', 'district' => 'Kishoreganj', 'division' => 'Dhaka'],
            ['upazila' => 'Mithamoin', 'district' => 'Kishoreganj', 'division' => 'Dhaka'],
            ['upazila' => 'Nikli', 'district' => 'Kishoreganj', 'division' => 'Dhaka'],
            ['upazila' => 'Pakundia', 'district' => 'Kishoreganj', 'division' => 'Dhaka'],
            ['upazila' => 'Tarail', 'district' => 'Kishoreganj', 'division' => 'Dhaka'],
            ['upazila' => 'Kalkini', 'district' => 'Madaripur', 'division' => 'Dhaka'],
            ['upazila' => 'Madaripur-S', 'district' => 'Madaripur', 'division' => 'Dhaka'],
            ['upazila' => 'Rajoira', 'district' => 'Madaripur', 'division' => 'Dhaka'],
            ['upazila' => 'Shibchar', 'district' => 'Madaripur', 'division' => 'Dhaka'],
            ['upazila' => 'Daulatpur', 'district' => 'Manikganj', 'division' => 'Dhaka'],
            ['upazila' => 'Ghior', 'district' => 'Manikganj', 'division' => 'Dhaka'],
            ['upazila' => 'Harirampur', 'district' => 'Manikganj', 'division' => 'Dhaka'],
            ['upazila' => 'Manikganj-S', 'district' => 'Manikganj', 'division' => 'Dhaka'],
            ['upazila' => 'Saturia', 'district' => 'Manikganj', 'division' => 'Dhaka'],
            ['upazila' => 'Shivalaya', 'district' => 'Manikganj', 'division' => 'Dhaka'],
            ['upazila' => 'Singair', 'district' => 'Manikganj', 'division' => 'Dhaka'],
            ['upazila' => 'Gazaria', 'district' => 'Munshiganj', 'division' => 'Dhaka'],
            ['upazila' => 'Lauhajong', 'district' => 'Munshiganj', 'division' => 'Dhaka'],
            ['upazila' => 'Munshiganj-S', 'district' => 'Munshiganj', 'division' => 'Dhaka'],
            ['upazila' => 'Sirajdikhan', 'district' => 'Munshiganj', 'division' => 'Dhaka'],
            ['upazila' => 'Sreenagar', 'district' => 'Munshiganj', 'division' => 'Dhaka'],
            ['upazila' => 'Tongibari', 'district' => 'Munshiganj', 'division' => 'Dhaka'],
            ['upazila' => 'Araihazar', 'district' => 'Narayanganj', 'division' => 'Dhaka'],
            ['upazila' => 'Bandar', 'district' => 'Narayanganj', 'division' => 'Dhaka'],
            ['upazila' => 'Narayanganj-S', 'district' => 'Narayanganj', 'division' => 'Dhaka'],
            ['upazila' => 'Rupganj', 'district' => 'Narayanganj', 'division' => 'Dhaka'],
            ['upazila' => 'Sonargaon', 'district' => 'Narayanganj', 'division' => 'Dhaka'],
            ['upazila' => 'Belabo', 'district' => 'Narshingdi', 'division' => 'Dhaka'],
            ['upazila' => 'Monohardi', 'district' => 'Narshingdi', 'division' => 'Dhaka'],
            ['upazila' => 'Narshingdi-S', 'district' => 'Narshingdi', 'division' => 'Dhaka'],
            ['upazila' => 'Palash', 'district' => 'Narshingdi', 'division' => 'Dhaka'],
            ['upazila' => 'Raipura', 'district' => 'Narshingdi', 'division' => 'Dhaka'],
            ['upazila' => 'Shibpur', 'district' => 'Narshingdi', 'division' => 'Dhaka'],
            ['upazila' => 'Baliakandi', 'district' => 'Rajbari', 'division' => 'Dhaka'],
            ['upazila' => 'Goalanda', 'district' => 'Rajbari', 'division' => 'Dhaka'],
            ['upazila' => 'Kallukhali', 'district' => 'Rajbari', 'division' => 'Dhaka'],
            ['upazila' => 'Pangsha', 'district' => 'Rajbari', 'division' => 'Dhaka'],
            ['upazila' => 'Rajbari-S', 'district' => 'Rajbari', 'division' => 'Dhaka'],
            ['upazila' => 'Bhedarganj', 'district' => 'Shariatpur', 'division' => 'Dhaka'],
            ['upazila' => 'Damuddya', 'district' => 'Shariatpur', 'division' => 'Dhaka'],
            ['upazila' => 'Goshairhat', 'district' => 'Shariatpur', 'division' => 'Dhaka'],
            ['upazila' => 'Janjira', 'district' => 'Shariatpur', 'division' => 'Dhaka'],
            ['upazila' => 'Naria', 'district' => 'Shariatpur', 'division' => 'Dhaka'],
            ['upazila' => 'Shariatpur-S', 'district' => 'Shariatpur', 'division' => 'Dhaka'],
            ['upazila' => 'Basail', 'district' => 'Tangail', 'division' => 'Dhaka'],
            ['upazila' => 'Bhuapur', 'district' => 'Tangail', 'division' => 'Dhaka'],
            ['upazila' => 'Delduar', 'district' => 'Tangail', 'division' => 'Dhaka'],
            ['upazila' => 'Dhanbari', 'district' => 'Tangail', 'division' => 'Dhaka'],
            ['upazila' => 'Ghatail', 'district' => 'Tangail', 'division' => 'Dhaka'],
            ['upazila' => 'Gopalpur', 'district' => 'Tangail', 'division' => 'Dhaka'],
            ['upazila' => 'Kalihati', 'district' => 'Tangail', 'division' => 'Dhaka'],
            ['upazila' => 'Madhupur', 'district' => 'Tangail', 'division' => 'Dhaka'],
            ['upazila' => 'Mirzapur', 'district' => 'Tangail', 'division' => 'Dhaka'],
            ['upazila' => 'Nagarpur', 'district' => 'Tangail', 'division' => 'Dhaka'],
            ['upazila' => 'Shakhipur', 'district' => 'Tangail', 'division' => 'Dhaka'],
            ['upazila' => 'Tangail-S', 'district' => 'Tangail', 'division' => 'Dhaka'],
            ['upazila' => 'Bagerhat-S', 'district' => 'Bagerhat', 'division' => 'Khulna'],
            ['upazila' => 'Chitalmari', 'district' => 'Bagerhat', 'division' => 'Khulna'],
            ['upazila' => 'Fakirhat', 'district' => 'Bagerhat', 'division' => 'Khulna'],
            ['upazila' => 'Kachua', 'district' => 'Bagerhat', 'division' => 'Khulna'],
            ['upazila' => 'Mollahat', 'district' => 'Bagerhat', 'division' => 'Khulna'],
            ['upazila' => 'Mongla', 'district' => 'Bagerhat', 'division' => 'Khulna'],
            ['upazila' => 'Morrelganj', 'district' => 'Bagerhat', 'division' => 'Khulna'], 
            ['upazila' => 'Rampal', 'district' => 'Bagerhat', 'division' => 'Khulna'],
            ['upazila' => 'Sharankhola', 'district' => 'Bagerhat', 'division' => 'Khulna'],
            ['upazila' => 'Alamdanga', 'district' => 'Chuadanga', 'division' => 'Khulna'],
            ['upazila' => 'Chuadanga-S', 'district' => 'Chuadanga', 'division' => 'Khulna'], 
            ['upazila' => 'Damurhuda', 'district' => 'Chuadanga', 'division' => 'Khulna'],
            ['upazila' => 'Jibannagar', 'district' => 'Chuadanga', 'division' => 'Khulna'],
            ['upazila' => 'Abhaynagar', 'district' => 'Jashore', 'division' => 'Khulna'],
            ['upazila' => 'Bagherpara', 'district' => 'Jashore', 'division' => 'Khulna'],
            ['upazila' => 'Chowgacha', 'district' => 'Jashore', 'division' => 'Khulna'],
            ['upazila' => 'Jashore-S', 'district' => 'Jashore', 'division' => 'Khulna'],
            ['upazila' => 'Jhikargacha', 'district' => 'Jashore', 'division' => 'Khulna'],
            ['upazila' => 'Keshabpur', 'district' => 'Jashore', 'division' => 'Khulna'],
            ['upazila' => 'Monirampur', 'district' => 'Jashore', 'division' => 'Khulna'],
            ['upazila' => 'Sarsha', 'district' => 'Jashore', 'division' => 'Khulna'],
            ['upazila' => 'Harinakunda', 'district' => 'Jhenaidah', 'division' => 'Khulna'],
            ['upazila' => 'Jhenaidah-S', 'district' => 'Jhenaidah', 'division' => 'Khulna'], 
            ['upazila' => 'Kaliganj', 'district' => 'Jhenaidah', 'division' => 'Khulna'],
            ['upazila' => 'Kotchandpur', 'district' => 'Jhenaidah', 'division' => 'Khulna'],
            ['upazila' => 'Moheshpur', 'district' => 'Jhenaidah', 'division' => 'Khulna'],
            ['upazila' => 'Shailkupa', 'district' => 'Jhenaidah', 'division' => 'Khulna'], 
            ['upazila' => 'Batiaghata', 'district' => 'Khulna', 'division' => 'Khulna'],
            ['upazila' => 'Dacope', 'district' => 'Khulna', 'division' => 'Khulna'],
            ['upazila' => 'Dighalia', 'district' => 'Khulna', 'division' => 'Khulna'],
            ['upazila' => 'Dumuria', 'district' => 'Khulna', 'division' => 'Khulna'],
            ['upazila' => 'Koira', 'district' => 'Khulna', 'division' => 'Khulna'],
            ['upazila' => 'Paikgacha', 'district' => 'Khulna', 'division' => 'Khulna'],
            ['upazila' => 'Phultala', 'district' => 'Khulna', 'division' => 'Khulna'],
            ['upazila' => 'Rupsa', 'district' => 'Khulna', 'division' => 'Khulna'],
            ['upazila' => 'Terokhada', 'district' => 'Khulna', 'division' => 'Khulna'],
            ['upazila' => 'Bheramara', 'district' => 'Kushtia', 'division' => 'Khulna'],
            ['upazila' => 'Daulatpur', 'district' => 'Kushtia', 'division' => 'Khulna'],
            ['upazila' => 'Khoksha', 'district' => 'Kushtia', 'division' => 'Khulna'],
            ['upazila' => 'Kumarkhali', 'district' => 'Kushtia', 'division' => 'Khulna'], 
            ['upazila' => 'Kushtia-S', 'district' => 'Kushtia', 'division' => 'Khulna'],
            ['upazila' => 'Mirpur', 'district' => 'Kushtia', 'division' => 'Khulna'],
            ['upazila' => 'Magura-S', 'district' => 'Magura', 'division' => 'Khulna'], 
            ['upazila' => 'Mohammadpur', 'district' => 'Magura', 'division' => 'Khulna'],
            ['upazila' => 'Salikha', 'district' => 'Magura', 'division' => 'Khulna'],
            ['upazila' => 'Sreepur', 'district' => 'Magura', 'division' => 'Khulna'],
            ['upazila' => 'Gangni', 'district' => 'Meherpur', 'division' => 'Khulna'], 
            ['upazila' => 'Meherpur-S', 'district' => 'Meherpur', 'division' => 'Khulna'],
            ['upazila' => 'Mujib Nagar', 'district' => 'Meherpur', 'division' => 'Khulna'], 
            ['upazila' => 'Kalia', 'district' => 'Narail', 'division' => 'Khulna'],
            ['upazila' => 'Lohagara', 'district' => 'Narail', 'division' => 'Khulna'],
            ['upazila' => 'Narail-S', 'district' => 'Narail', 'division' => 'Khulna'],
            ['upazila' => 'Assasuni', 'district' => 'Satkhira', 'division' => 'Khulna'],
            ['upazila' => 'Debhata', 'district' => 'Satkhira', 'division' => 'Khulna'],
            ['upazila' => 'Kalaroa', 'district' => 'Satkhira', 'division' => 'Khulna'],
            ['upazila' => 'Kaliganj', 'district' => 'Satkhira', 'division' => 'Khulna'],
            ['upazila' => 'Satkhira-S', 'district' => 'Satkhira', 'division' => 'Khulna'],
            ['upazila' => 'Shyamnagar', 'district' => 'Satkhira', 'division' => 'Khulna'],
            ['upazila' => 'Tala', 'district' => 'Satkhira', 'division' => 'Khulna'],
            ['upazila' => 'Bakshiganj', 'district' => 'Jamalpur', 'division' => 'Mymensingh'],
            ['upazila' => 'Dewanganj', 'district' => 'Jamalpur', 'division' => 'Mymensingh'],
            ['upazila' => 'Islampur', 'district' => 'Jamalpur', 'division' => 'Mymensingh'],
            ['upazila' => 'Jamalpur-S', 'district' => 'Jamalpur', 'division' => 'Mymensingh'],
            ['upazila' => 'Madariganj', 'district' => 'Jamalpur', 'division' => 'Mymensingh'],
            ['upazila' => 'Melendah', 'district' => 'Jamalpur', 'division' => 'Mymensingh'],
            ['upazila' => 'Sarishabari', 'district' => 'Jamalpur', 'division' => 'Mymensingh'],
            ['upazila' => 'Bhaluka', 'district' => 'Mymensingh', 'division' => 'Mymensingh'],
            ['upazila' => 'Dhobaura', 'district' => 'Mymensingh', 'division' => 'Mymensingh'],
            ['upazila' => 'Fulbaria', 'district' => 'Mymensingh', 'division' => 'Mymensingh'],
            ['upazila' => 'Gaffargaon', 'district' => 'Mymensingh', 'division' => 'Mymensingh'],
            ['upazila' => 'Gouripur', 'district' => 'Mymensingh', 'division' => 'Mymensingh'],
            ['upazila' => 'Haluaghat', 'district' => 'Mymensingh', 'division' => 'Mymensingh'],
            ['upazila' => 'Ishwarganj', 'district' => 'Mymensingh', 'division' => 'Mymensingh'],
            ['upazila' => 'Muktagacha', 'district' => 'Mymensingh', 'division' => 'Mymensingh'],
            ['upazila' => 'Mymensingh-S', 'district' => 'Mymensingh', 'division' => 'Mymensingh'],
            ['upazila' => 'Nandail', 'district' => 'Mymensingh', 'division' => 'Mymensingh'],
            ['upazila' => 'Phulpur', 'district' => 'Mymensingh', 'division' => 'Mymensingh'],
            ['upazila' => 'Tarakanda', 'district' => 'Mymensingh', 'division' => 'Mymensingh'],
            ['upazila' => 'Trishal', 'district' => 'Mymensingh', 'division' => 'Mymensingh'],
            ['upazila' => 'Atpara', 'district' => 'Netrokona', 'division' => 'Mymensingh'],
            ['upazila' => 'Barhatta', 'district' => 'Netrokona', 'division' => 'Mymensingh'],
            ['upazila' => 'Durgapur', 'district' => 'Netrokona', 'division' => 'Mymensingh'],
            ['upazila' => 'Kalmakanda', 'district' => 'Netrokona', 'division' => 'Mymensingh'],
            ['upazila' => 'Kendua', 'district' => 'Netrokona', 'division' => 'Mymensingh'],
            ['upazila' => 'Khaliajuri', 'district' => 'Netrokona', 'division' => 'Mymensingh'],
            ['upazila' => 'Madan', 'district' => 'Netrokona', 'division' => 'Mymensingh'],
            ['upazila' => 'Mohanganj', 'district' => 'Netrokona', 'division' => 'Mymensingh'],
            ['upazila' => 'Netrakona-S', 'district' => 'Netrokona', 'division' => 'Mymensingh'],
            ['upazila' => 'Purbadhala', 'district' => 'Netrokona', 'division' => 'Mymensingh'],
            ['upazila' => 'Jhenaigati', 'district' => 'Sherpur', 'division' => 'Mymensingh'],
            ['upazila' => 'Nakla', 'district' => 'Sherpur', 'division' => 'Mymensingh'],
            ['upazila' => 'Nalitabari', 'district' => 'Sherpur', 'division' => 'Mymensingh'],
            ['upazila' => 'Sherpur-S', 'district' => 'Sherpur', 'division' => 'Mymensingh'],
            ['upazila' => 'Sreebordi', 'district' => 'Sherpur', 'division' => 'Mymensingh'],
            ['upazila' => 'Adamdighi', 'district' => 'Bogura', 'division' => 'Rajshahi'],
            ['upazila' => 'Bogura-S', 'district' => 'Bogura', 'division' => 'Rajshahi'],
            ['upazila' => 'Dhunot', 'district' => 'Bogura', 'division' => 'Rajshahi'],
            ['upazila' => 'Dhupchancia', 'district' => 'Bogura', 'division' => 'Rajshahi'],
            ['upazila' => 'Gabtali', 'district' => 'Bogura', 'division' => 'Rajshahi'],
            ['upazila' => 'Kahaloo', 'district' => 'Bogura', 'division' => 'Rajshahi'],
            ['upazila' => 'Nandigram', 'district' => 'Bogura', 'division' => 'Rajshahi'],
            ['upazila' => 'Sariakandi', 'district' => 'Bogura', 'division' => 'Rajshahi'],
            ['upazila' => 'Shajahanpur', 'district' => 'Bogura', 'division' => 'Rajshahi'],
            ['upazila' => 'Sherpur', 'district' => 'Bogura', 'division' => 'Rajshahi'],
            ['upazila' => 'Shibganj', 'district' => 'Bogura', 'division' => 'Rajshahi'],
            ['upazila' => 'Sonatala', 'district' => 'Bogura', 'division' => 'Rajshahi'],
            ['upazila' => 'Bholahat', 'district' => 'Chapai Nawabganj', 'division' => 'Rajshahi'],
            ['upazila' => 'Gomostapur', 'district' => 'Chapai Nawabganj', 'division' => 'Rajshahi'],
            ['upazila' => 'Nachol', 'district' => 'Chapai Nawabganj', 'division' => 'Rajshahi'],
            ['upazila' => 'Nawabganj-S', 'district' => 'Chapai Nawabganj', 'division' => 'Rajshahi'],
            ['upazila' => 'Shibganj', 'district' => 'Chapai Nawabganj', 'division' => 'Rajshahi'],
            ['upazila' => 'Akkelpur', 'district' => 'Joypurhat', 'division' => 'Rajshahi'],
            ['upazila' => 'Joypurhat-S', 'district' => 'Joypurhat', 'division' => 'Rajshahi'], 
            ['upazila' => 'Kalai', 'district' => 'Joypurhat', 'division' => 'Rajshahi'],
            ['upazila' => 'Khetlal', 'district' => 'Joypurhat', 'division' => 'Rajshahi'],
            ['upazila' => 'Panchbibi', 'district' => 'Joypurhat', 'division' => 'Rajshahi'],
            ['upazila' => 'Atrai', 'district' => 'Naogaon', 'division' => 'Rajshahi'],
            ['upazila' => 'Badalgachi', 'district' => 'Naogaon', 'division' => 'Rajshahi'],
            ['upazila' => 'Dhamoirhat', 'district' => 'Naogaon', 'division' => 'Rajshahi'],
            ['upazila' => 'Manda', 'district' => 'Naogaon', 'division' => 'Rajshahi'],
            ['upazila' => 'Mohadevpur', 'district' => 'Naogaon', 'division' => 'Rajshahi'],
            ['upazila' => 'Naogaon-S', 'district' => 'Naogaon', 'division' => 'Rajshahi'],
            ['upazila' => 'Niamatpur', 'district' => 'Naogaon', 'division' => 'Rajshahi'],
            ['upazila' => 'Patnitala', 'district' => 'Naogaon', 'division' => 'Rajshahi'],
            ['upazila' => 'Porsha', 'district' => 'Naogaon', 'division' => 'Rajshahi'],
            ['upazila' => 'Raninagar', 'district' => 'Naogaon', 'division' => 'Rajshahi'],
            ['upazila' => 'Shapahar', 'district' => 'Naogaon', 'division' => 'Rajshahi'],
            ['upazila' => 'Bagatipara', 'district' => 'Natore', 'division' => 'Rajshahi'],
            ['upazila' => 'Baraigram', 'district' => 'Natore', 'division' => 'Rajshahi'],
            ['upazila' => 'Gurudaspur', 'district' => 'Natore', 'division' => 'Rajshahi'],
            ['upazila' => 'Lalpur', 'district' => 'Natore', 'division' => 'Rajshahi'],
            ['upazila' => 'Naldanga', 'district' => 'Natore', 'division' => 'Rajshahi'],
            ['upazila' => 'Natore-S', 'district' => 'Natore', 'division' => 'Rajshahi'], 
            ['upazila' => 'Singra', 'district' => 'Natore', 'division' => 'Rajshahi'],
            ['upazila' => 'Atghoria', 'district' => 'Pabna', 'division' => 'Rajshahi'],
            ['upazila' => 'Bera', 'district' => 'Pabna', 'division' => 'Rajshahi'],
            ['upazila' => 'Bhangura', 'district' => 'Pabna', 'division' => 'Rajshahi'],
            ['upazila' => 'Chatmohar', 'district' => 'Pabna', 'division' => 'Rajshahi'],
            ['upazila' => 'Faridpur', 'district' => 'Pabna', 'division' => 'Rajshahi'],
            ['upazila' => 'Ishwardi', 'district' => 'Pabna', 'division' => 'Rajshahi'],
            ['upazila' => 'Pabna-S', 'district' => 'Pabna', 'division' => 'Rajshahi'],
            ['upazila' => 'Santhia', 'district' => 'Pabna', 'division' => 'Rajshahi'],
            ['upazila' => 'Sujanagar', 'district' => 'Pabna', 'division' => 'Rajshahi'],
            ['upazila' => 'Bagha', 'district' => 'Rajshahi', 'division' => 'Rajshahi'],
            ['upazila' => 'Bagmara', 'district' => 'Rajshahi', 'division' => 'Rajshahi'],
            ['upazila' => 'Charghat', 'district' => 'Rajshahi', 'division' => 'Rajshahi'],
            ['upazila' => 'Durgapur', 'district' => 'Rajshahi', 'division' => 'Rajshahi'],
            ['upazila' => 'Godagari', 'district' => 'Rajshahi', 'division' => 'Rajshahi'],
            ['upazila' => 'Mohanpur', 'district' => 'Rajshahi', 'division' => 'Rajshahi'],
            ['upazila' => 'Paba', 'district' => 'Rajshahi', 'division' => 'Rajshahi'],
            ['upazila' => 'Puthia', 'district' => 'Rajshahi', 'division' => 'Rajshahi'],
            ['upazila' => 'Tanore', 'district' => 'Rajshahi', 'division' => 'Rajshahi'],
            ['upazila' => 'Belkuchi', 'district' => 'Sirajganj', 'division' => 'Rajshahi'],
            ['upazila' => 'Chowhali', 'district' => 'Sirajganj', 'division' => 'Rajshahi'],
            ['upazila' => 'Kamarkhand', 'district' => 'Sirajganj', 'division' => 'Rajshahi'],
            ['upazila' => 'Kazipur', 'district' => 'Sirajganj', 'division' => 'Rajshahi'],
            ['upazila' => 'Raiganj', 'district' => 'Sirajganj', 'division' => 'Rajshahi'],
            ['upazila' => 'Shahzadpur', 'district' => 'Sirajganj', 'division' => 'Rajshahi'],
            ['upazila' => 'Sirajganj-S', 'district' => 'Sirajganj', 'division' => 'Rajshahi'],
            ['upazila' => 'Tarash', 'district' => 'Sirajganj', 'division' => 'Rajshahi'],
            ['upazila' => 'Ullapara', 'district' => 'Sirajganj', 'division' => 'Rajshahi'],
            ['upazila' => 'Birampur', 'district' => 'Dinajpur', 'division' => 'Rangpur'],
            ['upazila' => 'Birganj', 'district' => 'Dinajpur', 'division' => 'Rangpur'],
            ['upazila' => 'Birol', 'district' => 'Dinajpur', 'division' => 'Rangpur'],
            ['upazila' => 'Bochaganj', 'district' => 'Dinajpur', 'division' => 'Rangpur'],
            ['upazila' => 'Chirirbandar', 'district' => 'Dinajpur', 'division' => 'Rangpur'],
            ['upazila' => 'Dinajpur-S', 'district' => 'Dinajpur', 'division' => 'Rangpur'],
            ['upazila' => 'Fulbari', 'district' => 'Dinajpur', 'division' => 'Rangpur'],
            ['upazila' => 'Ghoraghat', 'district' => 'Dinajpur', 'division' => 'Rangpur'],
            ['upazila' => 'Hakimpur', 'district' => 'Dinajpur', 'division' => 'Rangpur'],
            ['upazila' => 'Kaharol', 'district' => 'Dinajpur', 'division' => 'Rangpur'],
            ['upazila' => 'Khansama', 'district' => 'Dinajpur', 'division' => 'Rangpur'],
            ['upazila' => 'Nawabganj', 'district' => 'Dinajpur', 'division' => 'Rangpur'],
            ['upazila' => 'Parbatipur', 'district' => 'Dinajpur', 'division' => 'Rangpur'],
            ['upazila' => 'Fulchari', 'district' => 'Gaibandha', 'division' => 'Rangpur'],
            ['upazila' => 'Gaibandha-S', 'district' => 'Gaibandha', 'division' => 'Rangpur'],
            ['upazila' => 'Gobindaganj', 'district' => 'Gaibandha', 'division' => 'Rangpur'],
            ['upazila' => 'Palashbari', 'district' => 'Gaibandha', 'division' => 'Rangpur'],
            ['upazila' => 'Sadullapur', 'district' => 'Gaibandha', 'division' => 'Rangpur'],
            ['upazila' => 'Saghata', 'district' => 'Gaibandha', 'division' => 'Rangpur'], 
            ['upazila' => 'Sundarganj', 'district' => 'Gaibandha', 'division' => 'Rangpur'],
            ['upazila' => 'Bhurungamari', 'district' => 'Kurigram', 'division' => 'Rangpur'],
            ['upazila' => 'Chilmari', 'district' => 'Kurigram', 'division' => 'Rangpur'],
            ['upazila' => 'Fulbari', 'district' => 'Kurigram', 'division' => 'Rangpur'],
            ['upazila' => 'Kurigram-S', 'district' => 'Kurigram', 'division' => 'Rangpur'],
            ['upazila' => 'Nageswari', 'district' => 'Kurigram', 'division' => 'Rangpur'],
            ['upazila' => 'Rajarhat', 'district' => 'Kurigram', 'division' => 'Rangpur'], 
            ['upazila' => 'Rajibpur', 'district' => 'Kurigram', 'division' => 'Rangpur'],
            ['upazila' => 'Rowmari', 'district' => 'Kurigram', 'division' => 'Rangpur'],
            ['upazila' => 'Ulipur', 'district' => 'Kurigram', 'division' => 'Rangpur'],
            ['upazila' => 'Aditmari', 'district' => 'Lalmonirhat', 'division' => 'Rangpur'],
            ['upazila' => 'Hatibandha', 'district' => 'Lalmonirhat', 'division' => 'Rangpur'], 
            ['upazila' => 'Kaliganj', 'district' => 'Lalmonirhat', 'division' => 'Rangpur'],
            ['upazila' => 'Lalmonirhat-S', 'district' => 'Lalmonirhat', 'division' => 'Rangpur'],
            ['upazila' => 'Patgram', 'district' => 'Lalmonirhat', 'division' => 'Rangpur'],
            ['upazila' => 'Dimla', 'district' => 'Nilphamari', 'division' => 'Rangpur'],
            ['upazila' => 'Domar', 'district' => 'Nilphamari', 'division' => 'Rangpur'],
            ['upazila' => 'Jaldhaka', 'district' => 'Nilphamari', 'division' => 'Rangpur'],
            ['upazila' => 'Kishoreganj', 'district' => 'Nilphamari', 'division' => 'Rangpur'],
            ['upazila' => 'Nilphamari-S', 'district' => 'Nilphamari', 'division' => 'Rangpur'],
            ['upazila' => 'Sayedpur', 'district' => 'Nilphamari', 'division' => 'Rangpur'],
            ['upazila' => 'Atwari', 'district' => 'Panchagarh', 'division' => 'Rangpur'],
            ['upazila' => 'Boda', 'district' => 'Panchagarh', 'division' => 'Rangpur'],
            ['upazila' => 'Debiganj', 'district' => 'Panchagarh', 'division' => 'Rangpur'],
            ['upazila' => 'Panchagarh-S', 'district' => 'Panchagarh', 'division' => 'Rangpur'],
            ['upazila' => 'Tetulia', 'district' => 'Panchagarh', 'division' => 'Rangpur'],
            ['upazila' => 'Badarganj', 'district' => 'Rangpur', 'division' => 'Rangpur'],
            ['upazila' => 'Gangachara', 'district' => 'Rangpur', 'division' => 'Rangpur'],
            ['upazila' => 'Kaunia', 'district' => 'Rangpur', 'division' => 'Rangpur'],
            ['upazila' => 'Mithapukur', 'district' => 'Rangpur', 'division' => 'Rangpur'],
            ['upazila' => 'Pirgacha', 'district' => 'Rangpur', 'division' => 'Rangpur'],
            ['upazila' => 'Pirganj', 'district' => 'Rangpur', 'division' => 'Rangpur'],
            ['upazila' => 'Rangpur-S', 'district' => 'Rangpur', 'division' => 'Rangpur'],
            ['upazila' => 'Taraganj', 'district' => 'Rangpur', 'division' => 'Rangpur'],
            ['upazila' => 'Baliadangi', 'district' => 'Thakurgaon', 'division' => 'Rangpur'],
            ['upazila' => 'Haripur', 'district' => 'Thakurgaon', 'division' => 'Rangpur'],
            ['upazila' => 'Pirganj', 'district' => 'Thakurgaon', 'division' => 'Rangpur'],
            ['upazila' => 'Ranisankail', 'district' => 'Thakurgaon', 'division' => 'Rangpur'],
            ['upazila' => 'Thakurgaon-S', 'district' => 'Thakurgaon', 'division' => 'Rangpur'],
            ['upazila' => 'Azmiriganj', 'district' => 'Habiganj', 'division' => 'Sylhet'], 
            ['upazila' => 'Bahubal', 'district' => 'Habiganj', 'division' => 'Sylhet'],
            ['upazila' => 'Baniachong', 'district' => 'Habiganj', 'division' => 'Sylhet'],
            ['upazila' => 'Chunarughat', 'district' => 'Habiganj', 'division' => 'Sylhet'],
            ['upazila' => 'Habiganj-S', 'district' => 'Habiganj', 'division' => 'Sylhet'],
            ['upazila' => 'Lakhai', 'district' => 'Habiganj', 'division' => 'Sylhet'],
            ['upazila' => 'Madhabpur', 'district' => 'Habiganj', 'division' => 'Sylhet'],
            ['upazila' => 'Nabiganj', 'district' => 'Habiganj', 'division' => 'Sylhet'],
            ['upazila' => 'Sayestaganj', 'district' => 'Habiganj', 'division' => 'Sylhet'],
            ['upazila' => 'Barlekha', 'district' => 'Moulvibazar', 'division' => 'Sylhet'],
            ['upazila' => 'Juri', 'district' => 'Moulvibazar', 'division' => 'Sylhet'],
            ['upazila' => 'Kamalganj', 'district' => 'Moulvibazar', 'division' => 'Sylhet'],
            ['upazila' => 'Kulaura', 'district' => 'Moulvibazar', 'division' => 'Sylhet'],
            ['upazila' => 'Moulvibazar-S', 'district' => 'Moulvibazar', 'division' => 'Sylhet'],
            ['upazila' => 'Rajnagar', 'district' => 'Moulvibazar', 'division' => 'Sylhet'],
            ['upazila' => 'Sreemangal', 'district' => 'Moulvibazar', 'division' => 'Sylhet'],
            ['upazila' => 'Biswamvarpur', 'district' => 'Sunamganj', 'division' => 'Sylhet'],
            ['upazila' => 'Chatak', 'district' => 'Sunamganj', 'division' => 'Sylhet'],
            ['upazila' => 'Dakhin Sunamganj', 'district' => 'Sunamganj', 'division' => 'Sylhet'],
            ['upazila' => 'Derai', 'district' => 'Sunamganj', 'division' => 'Sylhet'],
            ['upazila' => 'Dharmapasha', 'district' => 'Sunamganj', 'division' => 'Sylhet'],
            ['upazila' => 'Doarabazar', 'district' => 'Sunamganj', 'division' => 'Sylhet'],
            ['upazila' => 'Jagannathpur', 'district' => 'Sunamganj', 'division' => 'Sylhet'],
            ['upazila' => 'Jamalganj', 'district' => 'Sunamganj', 'division' => 'Sylhet'],
            ['upazila' => 'Sulla', 'district' => 'Sunamganj', 'division' => 'Sylhet'],
            ['upazila' => 'Sunamganj-S', 'district' => 'Sunamganj', 'division' => 'Sylhet'],
            ['upazila' => 'Tahirpur', 'district' => 'Sunamganj', 'division' => 'Sylhet'],
            ['upazila' => 'Balaganj', 'district' => 'Sylhet', 'division' => 'Sylhet'],
            ['upazila' => 'Beanibazar', 'district' => 'Sylhet', 'division' => 'Sylhet'],
            ['upazila' => 'Biswanath', 'district' => 'Sylhet', 'division' => 'Sylhet'],
            ['upazila' => 'Companiganj', 'district' => 'Sylhet', 'division' => 'Sylhet'],
            ['upazila' => 'Dakshin Surma', 'district' => 'Sylhet', 'division' => 'Sylhet'],
            ['upazila' => 'Fenchuganj', 'district' => 'Sylhet', 'division' => 'Sylhet'],
            ['upazila' => 'Golapganj', 'district' => 'Sylhet', 'division' => 'Sylhet'],
            ['upazila' => 'Gowainghat', 'district' => 'Sylhet', 'division' => 'Sylhet'],
            ['upazila' => 'Jointiapur', 'district' => 'Sylhet', 'division' => 'Sylhet'],
            ['upazila' => 'Kanaighat', 'district' => 'Sylhet', 'division' => 'Sylhet'],
            ['upazila' => 'Osmaninagar', 'district' => 'Sylhet', 'division' => 'Sylhet'],
            ['upazila' => 'Sylhet-S', 'district' => 'Sylhet', 'division' => 'Sylhet'],
            ['upazila' => 'Zakiganj', 'district' => 'Sylhet', 'division' => 'Sylhet']
        ];
        foreach ($upazilasData as $data) {
            $district = DB::table('districts')->where('name', $data['district'])->first();

            DB::table('upazilas')->insert(
                [
                    'name' => $data['upazila'], 
                    'district_id' => $district->id,
                    'division_id' => $district->division_id
                ] 
            );
        }
    
    }
}
